"""followers

Revision ID: e6d045fb8d25
Revises: ce898a69f62b
Create Date: 2023-01-23 14:23:54.636545

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'e6d045fb8d25'
down_revision = 'ce898a69f62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('followed_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE followers SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
